# Generated by Django 2.2.5 on 2019-09-06 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyisim')),
                ('tracking_number', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Takip Kodu')),
                ('information', models.TextField(verbose_name='Açıklama')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
