# Generated by Django 2.2.5 on 2019-09-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
