# Generated by Django 2.2.5 on 2019-09-07 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tracking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-publishing_date']},
        ),
        migrations.AddField(
            model_name='tracking',
            name='status',
            field=models.TextField(default=1, verbose_name='Durum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='name',
            field=models.CharField(max_length=50, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Takip Kodu'),
        ),
    ]
