# Generated by Django 2.2.5 on 2019-09-08 06:32

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190907_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='phone_number',
            field=phone_field.models.PhoneField(default=1, max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Takip Kodu'),
        ),
    ]
