# Generated by Django 2.2.5 on 2019-09-08 06:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20190908_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=11),
        ),
    ]
