# Generated by Django 2.2.5 on 2019-09-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20190908_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
    ]
