# Generated by Django 2.2.5 on 2019-09-08 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20190908_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='Telefon Numarası'),
        ),
    ]
