# Generated by Django 2.2.5 on 2019-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20190908_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='information',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
    ]
